//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: escrow
// ----------------------------------------------------------------------------
pub mod escrow {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for escrow
    pub fn program_id() -> Pubkey {
        pubkey!("3WSjgWUKWhsENKJ1ibnbgvaiuQ8THJp4Mp7uGTUyeYeJ")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: BuyerTimeoutRefund
    // ....................................................................

    /// Main instruction struct for BuyerTimeoutRefund
    pub struct BuyerTimeoutRefundInstruction {
        pub accounts: BuyerTimeoutRefundInstructionAccountMetas,
        pub data: BuyerTimeoutRefundInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for BuyerTimeoutRefund instruction
    #[derive(Debug, Clone, Default)]
    pub struct BuyerTimeoutRefundInstructionAccountMetas {
        pub buyer: AccountMeta,

        pub deal: AccountMeta,

        pub escrow_token_account: AccountMeta,

        pub buyer_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for BuyerTimeoutRefund instruction
    #[derive(Debug, Clone)]
    pub struct BuyerTimeoutRefundInstructionAccounts {
        pub buyer: Pubkey,

        pub deal: Pubkey,

        pub escrow_token_account: Pubkey,

        pub buyer_token_account: Pubkey,
    }

    impl BuyerTimeoutRefundInstructionAccounts {
        pub fn new(
            buyer: Pubkey,

            deal: Pubkey,

            escrow_token_account: Pubkey,

            buyer_token_account: Pubkey,
        ) -> Self {
            Self {
                buyer,

                deal,

                escrow_token_account,

                buyer_token_account,
            }
        }
    }

    /// Instruction data for BuyerTimeoutRefund
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct BuyerTimeoutRefundInstructionData {}

    impl BuyerTimeoutRefundInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for BuyerTimeoutRefundInstruction
    impl BuyerTimeoutRefundInstruction {
        fn discriminator() -> [u8; 8] {
            [38u8, 221u8, 152u8, 97u8, 238u8, 39u8, 29u8, 167u8]
        }

        pub fn data(data: BuyerTimeoutRefundInstructionData) -> Self {
            Self {
                accounts: BuyerTimeoutRefundInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: BuyerTimeoutRefundInstructionAccounts) -> Self {
            self.accounts.buyer = AccountMeta::new(accounts.buyer, true);

            self.accounts.deal = AccountMeta::new(accounts.deal, false);

            self.accounts.escrow_token_account =
                AccountMeta::new(accounts.escrow_token_account, false);

            self.accounts.buyer_token_account =
                AccountMeta::new(accounts.buyer_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.buyer.clone());

            metas.push(self.accounts.deal.clone());

            metas.push(self.accounts.escrow_token_account.clone());

            metas.push(self.accounts.buyer_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CancelDeal
    // ....................................................................

    /// Main instruction struct for CancelDeal
    pub struct CancelDealInstruction {
        pub accounts: CancelDealInstructionAccountMetas,
        pub data: CancelDealInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CancelDeal instruction
    #[derive(Debug, Clone, Default)]
    pub struct CancelDealInstructionAccountMetas {
        pub buyer: AccountMeta,

        pub deal: AccountMeta,

        pub escrow_token_account: AccountMeta,

        pub buyer_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for CancelDeal instruction
    #[derive(Debug, Clone)]
    pub struct CancelDealInstructionAccounts {
        pub buyer: Pubkey,

        pub deal: Pubkey,

        pub escrow_token_account: Pubkey,

        pub buyer_token_account: Pubkey,
    }

    impl CancelDealInstructionAccounts {
        pub fn new(
            buyer: Pubkey,

            deal: Pubkey,

            escrow_token_account: Pubkey,

            buyer_token_account: Pubkey,
        ) -> Self {
            Self {
                buyer,

                deal,

                escrow_token_account,

                buyer_token_account,
            }
        }
    }

    /// Instruction data for CancelDeal
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CancelDealInstructionData {}

    impl CancelDealInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CancelDealInstruction
    impl CancelDealInstruction {
        fn discriminator() -> [u8; 8] {
            [158u8, 86u8, 193u8, 45u8, 168u8, 111u8, 48u8, 29u8]
        }

        pub fn data(data: CancelDealInstructionData) -> Self {
            Self {
                accounts: CancelDealInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CancelDealInstructionAccounts) -> Self {
            self.accounts.buyer = AccountMeta::new(accounts.buyer, true);

            self.accounts.deal = AccountMeta::new(accounts.deal, false);

            self.accounts.escrow_token_account =
                AccountMeta::new(accounts.escrow_token_account, false);

            self.accounts.buyer_token_account =
                AccountMeta::new(accounts.buyer_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.buyer.clone());

            metas.push(self.accounts.deal.clone());

            metas.push(self.accounts.escrow_token_account.clone());

            metas.push(self.accounts.buyer_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CloseDeal
    // ....................................................................

    /// Main instruction struct for CloseDeal
    pub struct CloseDealInstruction {
        pub accounts: CloseDealInstructionAccountMetas,
        pub data: CloseDealInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CloseDeal instruction
    #[derive(Debug, Clone, Default)]
    pub struct CloseDealInstructionAccountMetas {
        pub buyer: AccountMeta,

        pub deal: AccountMeta,

        pub escrow_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for CloseDeal instruction
    #[derive(Debug, Clone)]
    pub struct CloseDealInstructionAccounts {
        pub buyer: Pubkey,

        pub deal: Pubkey,

        pub escrow_token_account: Pubkey,
    }

    impl CloseDealInstructionAccounts {
        pub fn new(buyer: Pubkey, deal: Pubkey, escrow_token_account: Pubkey) -> Self {
            Self {
                buyer,

                deal,

                escrow_token_account,
            }
        }
    }

    /// Instruction data for CloseDeal
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CloseDealInstructionData {}

    impl CloseDealInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CloseDealInstruction
    impl CloseDealInstruction {
        fn discriminator() -> [u8; 8] {
            [157u8, 173u8, 33u8, 216u8, 146u8, 16u8, 65u8, 82u8]
        }

        pub fn data(data: CloseDealInstructionData) -> Self {
            Self {
                accounts: CloseDealInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CloseDealInstructionAccounts) -> Self {
            self.accounts.buyer = AccountMeta::new(accounts.buyer, true);

            self.accounts.deal = AccountMeta::new(accounts.deal, false);

            self.accounts.escrow_token_account =
                AccountMeta::new(accounts.escrow_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.buyer.clone());

            metas.push(self.accounts.deal.clone());

            metas.push(self.accounts.escrow_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateDeal
    // ....................................................................

    /// Main instruction struct for CreateDeal
    pub struct CreateDealInstruction {
        pub accounts: CreateDealInstructionAccountMetas,
        pub data: CreateDealInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateDeal instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateDealInstructionAccountMetas {
        pub buyer: AccountMeta,

        pub seller: AccountMeta,

        pub deal: AccountMeta,

        pub mint: AccountMeta,

        pub escrow_token_account: AccountMeta,

        pub config: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,

        pub rent: AccountMeta,
    }

    /// Account pubkeys for CreateDeal instruction
    #[derive(Debug, Clone)]
    pub struct CreateDealInstructionAccounts {
        pub buyer: Pubkey,

        pub seller: Pubkey,

        pub deal: Pubkey,

        pub mint: Pubkey,

        pub escrow_token_account: Pubkey,

        pub config: Pubkey,
    }

    impl CreateDealInstructionAccounts {
        pub fn new(
            buyer: Pubkey,

            seller: Pubkey,

            deal: Pubkey,

            mint: Pubkey,

            escrow_token_account: Pubkey,

            config: Pubkey,
        ) -> Self {
            Self {
                buyer,

                seller,

                deal,

                mint,

                escrow_token_account,

                config,
            }
        }
    }

    /// Instruction data for CreateDeal
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateDealInstructionData {
        pub deal_id: String,

        pub milestones: Vec<MilestoneInput>,

        pub total_amount: u64,

        /// Wallet that created the deal — required by on-chain handler (post-tier IDL).
        pub creator_wallet: Pubkey,
    }

    impl CreateDealInstructionData {
        pub fn new(
            deal_id: String,
            milestones: Vec<MilestoneInput>,
            total_amount: u64,
            creator_wallet: Pubkey,
        ) -> Self {
            Self {
                deal_id,

                milestones,

                total_amount,

                creator_wallet,
            }
        }
    }

    /// Implementation for CreateDealInstruction
    impl CreateDealInstruction {
        fn discriminator() -> [u8; 8] {
            [198u8, 212u8, 144u8, 151u8, 97u8, 56u8, 149u8, 113u8]
        }

        pub fn data(data: CreateDealInstructionData) -> Self {
            Self {
                accounts: CreateDealInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateDealInstructionAccounts) -> Self {
            self.accounts.buyer = AccountMeta::new(accounts.buyer, true);

            self.accounts.seller = AccountMeta::new_readonly(accounts.seller, false);

            self.accounts.deal = AccountMeta::new(accounts.deal, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.escrow_token_account =
                AccountMeta::new(accounts.escrow_token_account, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.rent = AccountMeta::new_readonly(
                pubkey!("SysvarRent111111111111111111111111111111111"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.buyer.clone());

            metas.push(self.accounts.seller.clone());

            metas.push(self.accounts.deal.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.escrow_token_account.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.rent.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: FundEscrow
    // ....................................................................

    /// Main instruction struct for FundEscrow
    pub struct FundEscrowInstruction {
        pub accounts: FundEscrowInstructionAccountMetas,
        pub data: FundEscrowInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for FundEscrow instruction
    #[derive(Debug, Clone, Default)]
    pub struct FundEscrowInstructionAccountMetas {
        pub buyer: AccountMeta,

        pub deal: AccountMeta,

        pub escrow_token_account: AccountMeta,

        pub buyer_token_account: AccountMeta,

        pub treasury_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for FundEscrow instruction
    #[derive(Debug, Clone)]
    pub struct FundEscrowInstructionAccounts {
        pub buyer: Pubkey,

        pub deal: Pubkey,

        pub escrow_token_account: Pubkey,

        pub buyer_token_account: Pubkey,

        pub treasury_token_account: Pubkey,
    }

    impl FundEscrowInstructionAccounts {
        pub fn new(
            buyer: Pubkey,

            deal: Pubkey,

            escrow_token_account: Pubkey,

            buyer_token_account: Pubkey,

            treasury_token_account: Pubkey,
        ) -> Self {
            Self {
                buyer,

                deal,

                escrow_token_account,

                buyer_token_account,

                treasury_token_account,
            }
        }
    }

    /// Instruction data for FundEscrow
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct FundEscrowInstructionData {
        pub amount: u64,
    }

    impl FundEscrowInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for FundEscrowInstruction
    impl FundEscrowInstruction {
        fn discriminator() -> [u8; 8] {
            [155u8, 18u8, 218u8, 141u8, 182u8, 213u8, 69u8, 201u8]
        }

        pub fn data(data: FundEscrowInstructionData) -> Self {
            Self {
                accounts: FundEscrowInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: FundEscrowInstructionAccounts) -> Self {
            self.accounts.buyer = AccountMeta::new(accounts.buyer, true);

            self.accounts.deal = AccountMeta::new(accounts.deal, false);

            self.accounts.escrow_token_account =
                AccountMeta::new(accounts.escrow_token_account, false);

            self.accounts.buyer_token_account =
                AccountMeta::new(accounts.buyer_token_account, false);

            self.accounts.treasury_token_account =
                AccountMeta::new(accounts.treasury_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.buyer.clone());

            metas.push(self.accounts.deal.clone());

            metas.push(self.accounts.escrow_token_account.clone());

            metas.push(self.accounts.buyer_token_account.clone());

            metas.push(self.accounts.treasury_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitConfig
    // ....................................................................

    /// Main instruction struct for InitConfig
    pub struct InitConfigInstruction {
        pub accounts: InitConfigInstructionAccountMetas,
        pub data: InitConfigInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitConfig instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitConfigInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitConfig instruction
    #[derive(Debug, Clone)]
    pub struct InitConfigInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,
    }

    impl InitConfigInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey) -> Self {
            Self { authority, config }
        }
    }

    /// Instruction data for InitConfig
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitConfigInstructionData {
        pub fee_bps: u16,
    }

    impl InitConfigInstructionData {
        pub fn new(fee_bps: u16) -> Self {
            Self { fee_bps }
        }
    }

    /// Implementation for InitConfigInstruction
    impl InitConfigInstruction {
        fn discriminator() -> [u8; 8] {
            [23u8, 235u8, 115u8, 232u8, 168u8, 96u8, 1u8, 231u8]
        }

        pub fn data(data: InitConfigInstructionData) -> Self {
            Self {
                accounts: InitConfigInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitConfigInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Refund
    // ....................................................................

    /// Main instruction struct for Refund
    pub struct RefundInstruction {
        pub accounts: RefundInstructionAccountMetas,
        pub data: RefundInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Refund instruction
    #[derive(Debug, Clone, Default)]
    pub struct RefundInstructionAccountMetas {
        pub buyer: AccountMeta,

        pub seller: AccountMeta,

        pub deal: AccountMeta,

        pub escrow_token_account: AccountMeta,

        pub buyer_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Refund instruction
    #[derive(Debug, Clone)]
    pub struct RefundInstructionAccounts {
        pub buyer: Pubkey,

        pub seller: Pubkey,

        pub deal: Pubkey,

        pub escrow_token_account: Pubkey,

        pub buyer_token_account: Pubkey,
    }

    impl RefundInstructionAccounts {
        pub fn new(
            buyer: Pubkey,

            seller: Pubkey,

            deal: Pubkey,

            escrow_token_account: Pubkey,

            buyer_token_account: Pubkey,
        ) -> Self {
            Self {
                buyer,

                seller,

                deal,

                escrow_token_account,

                buyer_token_account,
            }
        }
    }

    /// Instruction data for Refund
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RefundInstructionData {}

    impl RefundInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for RefundInstruction
    impl RefundInstruction {
        fn discriminator() -> [u8; 8] {
            [2u8, 96u8, 183u8, 251u8, 63u8, 208u8, 46u8, 46u8]
        }

        pub fn data(data: RefundInstructionData) -> Self {
            Self {
                accounts: RefundInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RefundInstructionAccounts) -> Self {
            self.accounts.buyer = AccountMeta::new(accounts.buyer, true);

            self.accounts.seller = AccountMeta::new(accounts.seller, true);

            self.accounts.deal = AccountMeta::new(accounts.deal, false);

            self.accounts.escrow_token_account =
                AccountMeta::new(accounts.escrow_token_account, false);

            self.accounts.buyer_token_account =
                AccountMeta::new(accounts.buyer_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.buyer.clone());

            metas.push(self.accounts.seller.clone());

            metas.push(self.accounts.deal.clone());

            metas.push(self.accounts.escrow_token_account.clone());

            metas.push(self.accounts.buyer_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ReleaseMilestone
    // ....................................................................

    /// Main instruction struct for ReleaseMilestone
    pub struct ReleaseMilestoneInstruction {
        pub accounts: ReleaseMilestoneInstructionAccountMetas,
        pub data: ReleaseMilestoneInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ReleaseMilestone instruction
    #[derive(Debug, Clone, Default)]
    pub struct ReleaseMilestoneInstructionAccountMetas {
        pub buyer: AccountMeta,

        pub deal: AccountMeta,

        pub escrow_token_account: AccountMeta,

        pub seller_token_account: AccountMeta,

        pub treasury_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for ReleaseMilestone instruction
    #[derive(Debug, Clone)]
    pub struct ReleaseMilestoneInstructionAccounts {
        pub buyer: Pubkey,

        pub deal: Pubkey,

        pub escrow_token_account: Pubkey,

        pub seller_token_account: Pubkey,

        pub treasury_token_account: Pubkey,
    }

    impl ReleaseMilestoneInstructionAccounts {
        pub fn new(
            buyer: Pubkey,

            deal: Pubkey,

            escrow_token_account: Pubkey,

            seller_token_account: Pubkey,

            treasury_token_account: Pubkey,
        ) -> Self {
            Self {
                buyer,

                deal,

                escrow_token_account,

                seller_token_account,

                treasury_token_account,
            }
        }
    }

    /// Instruction data for ReleaseMilestone
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ReleaseMilestoneInstructionData {
        pub milestone_index: u8,
    }

    impl ReleaseMilestoneInstructionData {
        pub fn new(milestone_index: u8) -> Self {
            Self { milestone_index }
        }
    }

    /// Implementation for ReleaseMilestoneInstruction
    impl ReleaseMilestoneInstruction {
        fn discriminator() -> [u8; 8] {
            [56u8, 2u8, 199u8, 164u8, 184u8, 108u8, 167u8, 222u8]
        }

        pub fn data(data: ReleaseMilestoneInstructionData) -> Self {
            Self {
                accounts: ReleaseMilestoneInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ReleaseMilestoneInstructionAccounts) -> Self {
            self.accounts.buyer = AccountMeta::new(accounts.buyer, true);

            self.accounts.deal = AccountMeta::new(accounts.deal, false);

            self.accounts.escrow_token_account =
                AccountMeta::new(accounts.escrow_token_account, false);

            self.accounts.seller_token_account =
                AccountMeta::new(accounts.seller_token_account, false);

            self.accounts.treasury_token_account =
                AccountMeta::new(accounts.treasury_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.buyer.clone());

            metas.push(self.accounts.deal.clone());

            metas.push(self.accounts.escrow_token_account.clone());

            metas.push(self.accounts.seller_token_account.clone());

            metas.push(self.accounts.treasury_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetAuthority
    // ....................................................................

    /// Main instruction struct for SetAuthority
    pub struct SetAuthorityInstruction {
        pub accounts: SetAuthorityInstructionAccountMetas,
        pub data: SetAuthorityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetAuthority instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetAuthorityInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for SetAuthority instruction
    #[derive(Debug, Clone)]
    pub struct SetAuthorityInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,
    }

    impl SetAuthorityInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey) -> Self {
            Self { authority, config }
        }
    }

    /// Instruction data for SetAuthority
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetAuthorityInstructionData {
        pub new_authority: Pubkey,
    }

    impl SetAuthorityInstructionData {
        pub fn new(new_authority: Pubkey) -> Self {
            Self { new_authority }
        }
    }

    /// Implementation for SetAuthorityInstruction
    impl SetAuthorityInstruction {
        fn discriminator() -> [u8; 8] {
            [133u8, 250u8, 37u8, 21u8, 110u8, 163u8, 26u8, 121u8]
        }

        pub fn data(data: SetAuthorityInstructionData) -> Self {
            Self {
                accounts: SetAuthorityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetAuthorityInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetFee
    // ....................................................................

    /// Main instruction struct for SetFee
    pub struct SetFeeInstruction {
        pub accounts: SetFeeInstructionAccountMetas,
        pub data: SetFeeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetFee instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetFeeInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for SetFee instruction
    #[derive(Debug, Clone)]
    pub struct SetFeeInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,
    }

    impl SetFeeInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey) -> Self {
            Self { authority, config }
        }
    }

    /// Instruction data for SetFee
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetFeeInstructionData {
        pub fee_bps: u16,
    }

    impl SetFeeInstructionData {
        pub fn new(fee_bps: u16) -> Self {
            Self { fee_bps }
        }
    }

    /// Implementation for SetFeeInstruction
    impl SetFeeInstruction {
        fn discriminator() -> [u8; 8] {
            [18u8, 154u8, 24u8, 18u8, 237u8, 214u8, 19u8, 80u8]
        }

        pub fn data(data: SetFeeInstructionData) -> Self {
            Self {
                accounts: SetFeeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetFeeInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetTreasury
    // ....................................................................

    /// Main instruction struct for SetTreasury
    pub struct SetTreasuryInstruction {
        pub accounts: SetTreasuryInstructionAccountMetas,
        pub data: SetTreasuryInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetTreasury instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetTreasuryInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for SetTreasury instruction
    #[derive(Debug, Clone)]
    pub struct SetTreasuryInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,
    }

    impl SetTreasuryInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey) -> Self {
            Self { authority, config }
        }
    }

    /// Instruction data for SetTreasury
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetTreasuryInstructionData {
        pub treasury: Pubkey,
    }

    impl SetTreasuryInstructionData {
        pub fn new(treasury: Pubkey) -> Self {
            Self { treasury }
        }
    }

    /// Implementation for SetTreasuryInstruction
    impl SetTreasuryInstruction {
        fn discriminator() -> [u8; 8] {
            [57u8, 97u8, 196u8, 95u8, 195u8, 206u8, 106u8, 136u8]
        }

        pub fn data(data: SetTreasuryInstructionData) -> Self {
            Self {
                accounts: SetTreasuryInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetTreasuryInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: Config
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Config {
    pub authority: Pubkey,

    pub treasury: Pubkey,

    pub fee_bps: u16,

    pub bump: u8,
}

impl Config {
    pub fn new(authority: Pubkey, treasury: Pubkey, fee_bps: u16, bump: u8) -> Self {
        Self {
            authority,

            treasury,

            fee_bps,

            bump,
        }
    }
}

/// Custom struct: Deal
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Deal {
    pub deal_id: String,

    pub buyer: Pubkey,

    pub seller: Pubkey,

    pub mint: Pubkey,

    pub escrow_token_account: Pubkey,

    pub total_amount: u64,

    pub funded_amount: u64,

    pub released_amount: u64,

    pub status: DealStatus,

    pub milestones: Vec<Milestone>,

    pub created_at: i64,

    pub funded_at: i64,

    pub updated_at: i64,

    pub fee_bps: u16,

    pub treasury: Pubkey,

    pub buyer_fee_paid: bool,

    pub bump: u8,
}

impl Deal {
    pub fn new(
        deal_id: String,

        buyer: Pubkey,

        seller: Pubkey,

        mint: Pubkey,

        escrow_token_account: Pubkey,

        total_amount: u64,

        funded_amount: u64,

        released_amount: u64,

        status: DealStatus,

        milestones: Vec<Milestone>,

        created_at: i64,

        funded_at: i64,

        updated_at: i64,

        fee_bps: u16,

        treasury: Pubkey,

        buyer_fee_paid: bool,

        bump: u8,
    ) -> Self {
        Self {
            deal_id,

            buyer,

            seller,

            mint,

            escrow_token_account,

            total_amount,

            funded_amount,

            released_amount,

            status,

            milestones,

            created_at,

            funded_at,

            updated_at,

            fee_bps,

            treasury,

            buyer_fee_paid,

            bump,
        }
    }
}

/// Custom enum: DealStatus
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum DealStatus {
    Created,

    Funded,

    InProgress,

    Completed,

    Refunded,

    Disputed,
}

/// Custom struct: Milestone
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Milestone {
    pub description: String,

    pub amount: u64,

    pub status: MilestoneStatus,

    pub confirmed_by: Option<Pubkey>,

    pub confirmed_at: Option<i64>,
}

impl Milestone {
    pub fn new(
        description: String,

        amount: u64,

        status: MilestoneStatus,

        confirmed_by: Option<Pubkey>,

        confirmed_at: Option<i64>,
    ) -> Self {
        Self {
            description,

            amount,

            status,

            confirmed_by,

            confirmed_at,
        }
    }
}

/// Custom struct: MilestoneInput
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MilestoneInput {
    pub description: String,

    pub amount: u64,
}

impl MilestoneInput {
    pub fn new(description: String, amount: u64) -> Self {
        Self {
            description,

            amount,
        }
    }
}

/// Custom enum: MilestoneStatus
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum MilestoneStatus {
    Pending,

    Completed,

    Released,
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
